version: '3.8'

services:

  couchdb:
    image: couchdb:latest
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb-data:/opt/couchdb/data

volumes:
  couchdb-data: